In [3]:
import numpy as np
epochs = 2
inputLayerSize, hiddenLayerSize, outputLayerSize = 2,3,1
L=0.1
x=np.array([[0,0],[0,1],[1,0],[1,1]])
y=np.array([[0],[1],[1],[0]])
def Sigmoid(x): return 1/(1+np.exp(-x))
def Sigmoid_(x): return x*(1-x)
hiddenweights = np.random.uniform(size=(inputLayerSize,hiddenLayerSize))
print("----Hidden Layer Weights----")
print("xxxxxxxxxxxxxxxx")
outputweights = np.random.uniform(size=(hiddenLayerSize,outputLayerSize))
print("----Output Layer Weights----")
print("xxxxxxxxxxxxxxxx")
for i in range(epochs):
    hiddenresult = Sigmoid(np.dot(x,hiddenweights))
    print("----Hidden Layer Weights----")
    print("Hidden Result")
    print("xxxxxxxxxxxxx")
    output=np.dot(hiddenresult,outputweights)
    print("----output----")
    print(output)
    print("xxxxxxxxxxxxx")
    error=y-output
    print("----error----")
    print(error)
    print("xxxxxxxxxxxxx")
    dz=error*L
    print("----Chnage in Error----")
    print(dz)
    print("xxxxxxxxxxxxx")
    outputweights+=hiddenresult.T.dot(dz)
    print("----Change in output weights----")
    print(outputweights)
    print("xxxxxxxxxxxxx")
    dhiddenres=dz.dot(outputweights.T)*Sigmoid_(hiddenresult)
    print("----Change in Hidden Result----")
    print(dhiddenres)
    print("xxxxxxxxxxxxx")
    hiddenweights+=x.T.dot(dhiddenres)
    print("----Change in Hidden Weights----")
    print(hiddenweights)

----Hidden Layer Weights----
xxxxxxxxxxxxxxxx
----Output Layer Weights----
xxxxxxxxxxxxxxxx
----Hidden Layer Weights----
Hidden Result
xxxxxxxxxxxxx
----output----
[[0.51369378]
 [0.71509456]
 [0.59569269]
 [0.77931898]]
xxxxxxxxxxxxx
----error----
[[-0.51369378]
 [ 0.28490544]
 [ 0.40430731]
 [-0.77931898]]
xxxxxxxxxxxxx
----Chnage in Error----
[[-0.05136938]
 [ 0.02849054]
 [ 0.04043073]
 [-0.0779319 ]]
xxxxxxxxxxxxx
----Change in output weights----
[[0.00124495]
 [0.84040686]
 [0.06466665]]
xxxxxxxxxxxxx
----Change in Hidden Result----
[[-1.59880127e-05 -1.07927944e-02 -8.30471442e-04]
 [ 7.53032192e-06  4.98503319e-03  4.32375926e-04]
 [ 1.20051759e-05  8.24900331e-03  6.52239024e-04]
 [-1.67471981e-05 -1.15760818e-02 -1.15368880e-03]]
xxxxxxxxxxxxx
----Change in Hidden Weights----
[[0.4355151  0.34005597 0.09182706]
 [0.81957922 0.86200752 0.50483678]]
----Hidden Layer Weights----
Hidden Result
xxxxxxxxxxxxx
----output----
[[0.45315923]
 [0.63206318]
 [0.52554189]
 [0.68885367]]
x